repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: helm/*
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: ^(tests)/
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety # no official one available
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
        files: requirements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests==0.1.13
          - types-jsonschema==3.2.0
        args: [ --strict, --implicit-reexport ]
        files: src
