[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
files = "src"
strict = true
implicit_reexport = true

[[tool.mypy.overrides]]
module = []
ignore_missing_imports = true

[tool.flake8]
max-line-length = 120

[tool.bandit]
recursive = true
