on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1
      - name: Install dependecies
        run: poetry install
      - name: Execute pre-commit
        run: poetry run pre-commit run -a --color=always --show-diff-on-failure
      - name: Execute Unit Tests
        run: poetry run make test
