on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Execute pre-commit
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pre-commit run -a --color=always --show-diff-on-failure
