name: Push to GCR GitHub Action
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'main'
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
      - name: Push image with commit hash tag
        uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: ${{ github.event.repository.name }}
          image_tag: ${{ github.sha }}
          dockerfile: ./Dockerfile
      - name: Push image with latest tag
        uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: ${{ github.event.repository.name }}
          image_tag: latest
          dockerfile: ./Dockerfile
